# Generated by Django 5.0.6 on 2024-05-25 20:04

import server.models
import server.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_category_options_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_banner_upload_path),
        ),
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_icon_upload_path, validators=[server.validators.validate_icon_image]),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=server.models.server_icon_upload_path),
        ),
    ]
